### ISSUE TITLE
Update Deployment to apps/v1 for K8s 1.16

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-vcenter-connector#29]
Update Deployment to apps/v1 for K8s 1.16

See yaml/kubernetes/connector-dep.yml

**Comment by martindekov** [comment]
I can update this. Will try to update the same for kafka-connector.

**Comment by alexellis** [comment]
Thank you

cc @embano1 @rgee0

**Comment by martindekov** [comment]
Missed that Simon updated the kafka-connector I reviewed it actually :+1:
